// src/app/layout.tsx
import '@/styles/globals.css';
import type { Metadata } from 'next';
import { SidebarProvider } from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/app-sidebar';
//import { SidebarTrigger } from '@/components/ui/sidebar-trigger';
import { ConvexProvider } from '@/components/providers/convex-provider';

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

// If you keep hitting SSR/prerender issues, you can enable this:
// export const dynamic = 'force-dynamic';

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="min-h-screen antialiased">
        {/* Provide Convex only on the client; safe to include here */}
        <ConvexProvider>
          <SidebarProvider>
            <div className="flex min-h-screen">
              <AppSidebar />
              <div className="flex flex-1 flex-col">
                <header className="h-14 flex items-center px-4">
                  {/* <SidebarTrigger /> */}
                </header>
                <main className="flex-1 p-4">{children}</main>
              </div>
            </div>
          </SidebarProvider>
        </ConvexProvider>
      </body>
    </html>
  );
}
