// app/layout.tsx
import "@/styles/globals.css"; // Tailwind v4: this file should have: @import "tailwindcss";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";


export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={geist.variable}>
      <body className="min-h-screen antialiased">
        <SidebarProvider>
          <div className="flex min-h-screen">
            {/* Sidebar column */}
            <AppSidebar />

            {/* Main column */}
            <div className="flex flex-1 flex-col">
              <header className="h-14 flex items-center px-4">
                <SidebarTrigger />
              </header>

              <main className="flex-1 p-4">{children}</main>
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
